import { defineStore } from 'pinia'
import type { Product } from '../types'

export const useProductsStore = defineStore('products', {
  state: () => ({
    products: [
      {
        id: 'coconut',
        name: 'Coconut',
        category: 'coconut' as const,
        tagline: 'The Fruit of a Thousand Uses',
        description:
          'Our coconuts are grown in rich tropical soil and harvested at peak maturity for retail and processing. Whole mature fruit ships first; after harvest we plan farm-direct coconut milk, toasted coconut chips, and cold-pressed coconut oil for homes, chefs, and food manufacturers.',
        benefits: [
          'Harvested at full maturity for retail and processing',
          'Naturally grown, chemical-free',
          'Whole fruit SKU for trade and kitchens',
          'Milk, chips, and oil planned after first harvest',
        ],
        icon: 'coconut',
        color: '#7B4F2E',
        bgColor: '#FDF5EE',
        available: true,
        waitlist: true,
        availabilityNote: 'First harvest forecast for June 2027',
        image: '/images/products/trovara-fresh-coconut.jpg',
        imageAlt: 'Trovara Fresh Coconut — naturally grown, responsibly farmed',
        specs: [
          { label: 'Fresh SKU', value: 'TRV-COC-PIECE · whole mature coconut' },
          { label: 'Processed SKUs', value: 'TRV-COC-MILK · TRV-COC-CHIPS · TRV-COC-OIL (planned)' },
          { label: 'Packaging', value: 'Mesh bags (25-50 kg) or custom bulk; retail packs for processed lines' },
          { label: 'Shelf life', value: '3-4 weeks at ambient; longer with cold chain; processed packs TBD' },
          { label: 'First harvest', value: 'June 2027 (forecast)' },
          { label: 'MOQ', value: 'Contact for volume-based minimums' },
          { label: 'Delivery', value: 'Nationwide across Nigeria (planned once supply opens)' },
        ],
      },
      {
        id: 'plantain',
        name: 'Plantain',
        category: 'plantain' as const,
        tagline: 'The World\'s Most Versatile Staple',
        description:
          'Our plantains are grown across rich tropical soil and harvested at the perfect stage - green for cooking, ripe for sweeter preparations. Starchier and heartier than regular bananas, plantains are a dietary staple across Africa, the Caribbean, and Latin America. After first harvest we plan dried plantain chips and milled plantain flour from the same plantation fruit.',
        benefits: [
          'High in resistant starch and complex carbohydrates',
          'Rich in potassium, vitamin C, and fiber',
          'Versatile: boiled, fried, dried into chips, or milled into flour',
          'Lower glycemic index than regular bananas',
          'No artificial ripening - grown and harvested naturally',
          'Chips and flour planned after first harvest',
        ],
        icon: 'plantain',
        color: '#C8841A',
        bgColor: '#FEFAED',
        available: true,
        waitlist: true,
        availabilityNote: 'First harvest forecast for March 2027',
        image: '/images/products/trovara-fresh-plantain.jpg',
        imageAlt: 'Trovara Fresh Plantain — naturally grown, responsibly farmed',
        specs: [
          { label: 'Fresh SKU', value: 'TRV-PLT-BUNCH · green or ripe whole fruit' },
          { label: 'Processed SKUs', value: 'TRV-DRP-PACK · dried chips · TRV-PLF-PACK · flour (planned)' },
          { label: 'Packaging', value: 'Graded cartons: 15 kg or 25 kg; retail packs for chips and flour' },
          { label: 'Shelf life', value: 'Green: 7-10 days; ripe: 3-5 days; chips/flour: up to 12 months' },
          { label: 'First harvest', value: 'March 2027 (forecast)' },
          { label: 'MOQ', value: 'Contact for product-specific minimums' },
          { label: 'Delivery', value: 'Nationwide across Nigeria (planned once supply opens)' },
        ],
      },
      {
        id: 'poultry',
        name: 'Pasture-raised Chicken',
        category: 'poultry' as const,
        tagline: 'Grass-fed. Pasture-raised. Grown with care.',
        description:
          'Our chickens are pasture-raised on open grass and fed a natural grass-and-grain diet with clean water. They are never caged and receive no growth hormones. Join the waitlist to be contacted when our first dressed birds are ready.',
        benefits: [
          'Grass-fed and pasture-raised',
          'Natural grass-and-grain diet',
          'No growth hormones',
          'Whole dressed birds and pre-cut options',
        ],
        icon: 'poultry',
        color: '#1A6B3C',
        bgColor: '#EDF7F1',
        available: true,
        waitlist: true,
        availabilityNote: 'First supply forecast for December 2026',
        image: '/images/products/pasture-raised-chicken.jpg',
        imageAlt: 'Trovara pasture-raised chickens foraging on open grass',
        specs: [
          { label: 'SKUs', value: 'TRV-CHK-BIRD · whole dressed birds; cuts on request' },
          { label: 'Packaging', value: 'Whole dressed birds; pre-cut options available on request' },
          { label: 'Shelf life', value: 'Fresh dressed birds: 3-5 days refrigerated; longer frozen' },
          { label: 'First supply', value: 'December 2026 (forecast)' },
          { label: 'MOQ', value: 'Contact for recurring supply contracts' },
          { label: 'Delivery', value: 'Nationwide across Nigeria (planned once supply opens)' },
        ],
      },
      {
        id: 'eggs',
        name: 'Eggs',
        category: 'eggs' as const,
        tagline: 'Taste what an egg is supposed to be.',
        description:
          'Our hens live outdoors on open pasture every day - rotated across fresh grass, never caged, never crammed into a shed. They forage on natural feed and clean water, with no antibiotics and no hormones. Eggs are hand-collected at dawn and graded before they leave the farm, so every deep-golden yolk carries the taste of the open pasture.',
        benefits: [
          'Genuinely pasture-raised - hens on grass every day',
          'Deep-golden, richer-tasting yolks',
          'No antibiotics, no hormones, ever',
          'Hand-collected at dawn and date-stamped',
        ],
        icon: 'eggs',
        color: '#D98A2B',
        bgColor: '#FEF6E7',
        available: true,
        waitlist: true,
        availabilityNote: 'Join the waitlist for first availability',
        image: '/images/products/trovara-fresh-eggs.jpg',
        imageAlt: 'Trovara Fresh Eggs — pasture-raised eggs you can trust',
        specs: [
          { label: 'SKUs', value: 'TRV-EGG-CRATE · crate of 30 pasture-raised eggs' },
          { label: 'Packaging', value: 'Crates of 30; half-crates on request' },
          { label: 'Freshness', value: 'Collected at dawn; date-stamped per crate' },
          { label: 'Delivery', value: 'Nationwide across Nigeria (planned once supply opens)' },
          { label: 'MOQ', value: 'To be confirmed when supply opens; volume pricing for trade' },
        ],
      },
      {
        id: 'palm-oil',
        name: 'Palm Oil',
        category: 'palm-oil' as const,
        tagline: 'A Nigerian staple, grown with care.',
        description:
          'Trovara palm oil is planned from fruit grown within our regenerative farm system. Our first harvest is forecast for December 2026. Join the waitlist for harvest updates, pack sizes, and first access when supply opens.',
        benefits: [
          'Farm-grown oil palm fruit',
          'Traceable harvest and processing',
          'Retail and food-service formats planned',
          'Nationwide delivery planned across Nigeria',
        ],
        icon: 'palm',
        color: '#9A4D1A',
        bgColor: '#FFF4E8',
        available: true,
        waitlist: true,
        availabilityNote: 'First harvest forecast for December 2026',
        image: '/images/products/trovara-fresh-palm-oil.jpg',
        imageAlt: 'Trovara Fresh Palm Oil — naturally grown, responsibly farmed',
        specs: [
          { label: 'SKUs', value: 'TRV-POL-1L · TRV-POL-BULK (planned)' },
          { label: 'Packaging', value: 'Retail bottles and food-service bulk formats to be confirmed' },
          { label: 'First harvest', value: 'December 2026 (forecast)' },
          { label: 'MOQ', value: 'To be confirmed before supply opens' },
          { label: 'Delivery', value: 'Nationwide across Nigeria (planned once supply opens)' },
        ],
      },
      {
        id: 'coming-soon',
        name: 'More Coming Soon',
        category: 'coming-soon' as const,
        tagline: 'The harvest never stops growing',
        description:
          'Trovara Farm is expanding carefully. We are developing new crop lines and formats to follow our first harvest windows. Stay close - more will open as each line is ready.',
        benefits: [
          'New crop varieties in development',
          'Expanding into processing and packaging',
          'Additional formats after first harvests',
          'Building long-term trade partnerships',
        ],
        icon: 'sprout',
        color: '#2D9960',
        bgColor: '#EDF7F1',
        available: false,
      },
    ] as Product[],
  }),

  getters: {
    availableProducts: (state) => state.products.filter((p) => p.available && p.category !== 'coming-soon'),
    allProducts: (state) => state.products,
    getProductById: (state) => (id: string) => state.products.find((p) => p.id === id),
  },
})
