import { defineStore } from 'pinia'
import type { Product } from '../types'

export const useProductsStore = defineStore('products', {
  state: () => ({
    products: [
      {
        id: 'coconut',
        name: 'Coconut',
        category: 'coconut' as const,
        tagline: 'The Fruit of a Thousand Uses',
        description:
          'Our coconuts are grown in rich tropical soil, harvested at peak maturity to deliver maximum sweetness, water content, and nutritional value. From fresh coconut water to dried copra, every coconut from Trovara Farm tells the story of the earth it grew in.',
        benefits: [
          'Rich in electrolytes and hydration',
          'Naturally sweet, chemical-free',
          'Harvested at full maturity',
          'Multi-purpose: water, flesh, oil, husk',
        ],
        icon: 'coconut',
        color: '#7B4F2E',
        bgColor: '#FDF5EE',
        available: true,
        availabilityNote: 'First harvest forecast for June 2027',
        specs: [
          { label: 'SKUs', value: 'TRV-COC-MATURE · whole mature coconut' },
          { label: 'Packaging', value: 'Mesh bags (25-50 kg) or custom bulk' },
          { label: 'Shelf life', value: '3-4 weeks at ambient; longer with cold chain' },
          { label: 'First harvest', value: 'June 2027 (forecast)' },
          { label: 'MOQ', value: 'Contact for volume-based minimums' },
          { label: 'Delivery', value: 'Nationwide across Nigeria' },
        ],
        orderTiers: [
          {
            id: 'one-time',
            name: 'One-Time Order',
            period: 'per order · quote-based',
            description: 'A single delivery sized to your needs - homes, shops, or events.',
            features: [
              'Order any volume',
              'Fresh, mature coconuts',
              'Nationwide delivery across Nigeria',
            ],
            ctaLabel: 'Order on WhatsApp',
            whatsappMessage:
              "Hi Trovara Farm, I'd like to place a one-time coconut order. Please share pricing and availability.",
          },
          {
            id: 'recurring',
            name: 'Recurring Supply',
            period: 'weekly or monthly',
            description: 'A standing order delivered on a schedule - ideal for shops, juice bars & kitchens.',
            features: [
              'Priority harvest allocation',
              'Locked-in supply schedule',
              'Preferential recurring pricing',
              'Pause or adjust anytime',
            ],
            ctaLabel: 'Set Up Recurring Supply',
            popular: true,
            whatsappMessage:
              "Hi Trovara Farm, I'd like to set up a recurring coconut supply. Please share subscription pricing and scheduling.",
          },
        ],
      },
      {
        id: 'plantain',
        name: 'Plantain',
        category: 'plantain' as const,
        tagline: 'The World\'s Most Versatile Staple',
        description:
          'Our plantains are grown across rich tropical soil and harvested at the perfect stage - green for cooking, ripe for sweeter preparations. Starchier and heartier than regular bananas, plantains are a dietary staple across Africa, the Caribbean, and Latin America. From boiled and fried to dried and milled into flour, every plantain from Trovara Farm is grown with zero synthetic chemicals and harvested to export-grade standards.',
        benefits: [
          'High in resistant starch and complex carbohydrates',
          'Rich in potassium, vitamin C, and fiber',
          'Versatile: boiled, fried, dried, or milled into flour',
          'Lower glycemic index than regular bananas',
          'No artificial ripening - grown and harvested naturally',
          'Export-grade quality for local and international markets',
        ],
        icon: 'plantain',
        color: '#C8841A',
        bgColor: '#FEFAED',
        available: true,
        availabilityNote: 'First harvest forecast for March 2027',
        image: '/images/products/fresh-plantain.jpg',
        imageAlt: 'Fresh green Trovara plantain packed in a graded carton',
        specs: [
          { label: 'SKUs', value: 'TRV-PLT-GREEN · TRV-PLT-RIPE · green or ripe whole fruit' },
          { label: 'Packaging', value: 'Graded cartons: 15 kg or 25 kg; pre-cut options available on request' },
          { label: 'Shelf life', value: 'Green: 7-10 days; ripe: 3-5 days; flour: 12 months' },
          { label: 'First harvest', value: 'March 2027 (forecast)' },
          { label: 'MOQ', value: 'Contact for product-specific minimums' },
          { label: 'Delivery', value: 'Nationwide across Nigeria' },
        ],
        orderTiers: [
          {
            id: 'one-time',
            name: 'One-Time Order',
            period: 'per order · quote-based',
            description: 'A single delivery of green, ripe, chips, or flour - sized to your needs.',
            features: [
              'Green, ripe, chips or flour',
              'Graded, export-quality',
              'Nationwide delivery across Nigeria',
            ],
            ctaLabel: 'Order on WhatsApp',
            whatsappMessage:
              "Hi Trovara Farm, I'd like to place a one-time plantain order. Please share pricing and availability.",
          },
          {
            id: 'recurring',
            name: 'Recurring Supply',
            period: 'weekly or monthly',
            description: 'A standing order delivered on a schedule - ideal for kitchens, retailers & processors.',
            features: [
              'Priority harvest allocation',
              'Locked-in supply schedule',
              'Preferential recurring pricing',
              'Pause or adjust anytime',
            ],
            ctaLabel: 'Set Up Recurring Supply',
            popular: true,
            whatsappMessage:
              "Hi Trovara Farm, I'd like to set up a recurring plantain supply. Please share subscription pricing and scheduling.",
          },
        ],
      },
      {
        id: 'poultry',
        name: 'Pasture-raised Chicken',
        category: 'poultry' as const,
        tagline: 'Grass-fed. Pasture-raised. Grown with care.',
        description:
          'Our chickens are pasture-raised on open grass and fed a natural grass-and-grain diet with clean water. They are never caged and receive no growth hormones. Join the waitlist to be contacted when our first dressed birds are ready.',
        benefits: [
          'Grass-fed and pasture-raised',
          'Natural grass-and-grain diet',
          'No growth hormones',
          'Whole dressed birds and pre-cut options',
        ],
        icon: 'poultry',
        color: '#1A6B3C',
        bgColor: '#EDF7F1',
        available: true,
        waitlist: true,
        availabilityNote: 'Target first supply: December 2026',
        image: '/images/products/pasture-raised-chicken.jpg',
        imageAlt: 'Trovara pasture-raised chickens foraging on open grass',
        specs: [
          { label: 'SKUs', value: 'TRV-CHK-WHOLE · TRV-CHK-CUT' },
          { label: 'Packaging', value: 'Whole dressed birds; pre-cut options available on request' },
          { label: 'Shelf life', value: 'Fresh dressed birds: 3-5 days refrigerated; longer frozen' },
          { label: 'Target supply', value: 'December 2026' },
          { label: 'MOQ', value: 'Contact for recurring supply contracts' },
          { label: 'Delivery', value: 'Nationwide across Nigeria' },
        ],
      },
      {
        id: 'eggs',
        name: 'Eggs',
        category: 'eggs' as const,
        tagline: 'Taste what an egg is supposed to be.',
        description:
          'Our hens live outdoors on open pasture every day - rotated across fresh grass, never caged, never crammed into a shed. They forage on natural feed and clean water, with no antibiotics and no hormones. Eggs are hand-collected at dawn and graded before they leave the farm, so every deep-golden yolk carries the taste of the open pasture.',
        benefits: [
          'Genuinely pasture-raised - hens on grass every day',
          'Deep-golden, richer-tasting yolks',
          'No antibiotics, no hormones, ever',
          'Hand-collected at dawn and date-stamped',
        ],
        icon: 'eggs',
        color: '#D98A2B',
        bgColor: '#FEF6E7',
        available: true,
        waitlist: true,
        availabilityNote: 'Join the waitlist for first availability',
        specs: [
          { label: 'SKUs', value: 'TRV-EGG-30 · crate of 30 pasture-raised eggs' },
          { label: 'Packaging', value: 'Crates of 30; half-crates on request' },
          { label: 'Freshness', value: 'Collected at dawn; date-stamped per crate' },
          { label: 'Delivery', value: 'Nationwide across Nigeria' },
          { label: 'MOQ', value: 'None for home orders; volume pricing for trade' },
        ],
      },
      {
        id: 'palm-oil',
        name: 'Palm Oil',
        category: 'palm-oil' as const,
        tagline: 'A Nigerian staple, grown with care.',
        description:
          'Trovara palm oil is planned from fruit grown within our regenerative farm system. Our first harvest is forecast for December 2026. Join the waitlist for harvest updates, pack sizes, and first access when supply opens.',
        benefits: [
          'Farm-grown oil palm fruit',
          'Traceable harvest and processing',
          'Retail and food-service formats planned',
          'Nationwide delivery across Nigeria',
        ],
        icon: 'palm',
        color: '#9A4D1A',
        bgColor: '#FFF4E8',
        available: true,
        waitlist: true,
        availabilityNote: 'First harvest forecast for December 2026',
        specs: [
          { label: 'SKUs', value: 'TRV-POL-1L · TRV-POL-BULK (planned)' },
          { label: 'Packaging', value: 'Retail bottles and food-service bulk formats to be confirmed' },
          { label: 'First harvest', value: 'December 2026 (forecast)' },
          { label: 'MOQ', value: 'To be confirmed before supply opens' },
          { label: 'Delivery', value: 'Nationwide across Nigeria' },
        ],
      },
      {
        id: 'coming-soon',
        name: 'More Coming Soon',
        category: 'coming-soon' as const,
        tagline: 'The harvest never stops growing',
        description:
          'Trovara Farm is constantly expanding. We are actively developing new crop lines and agricultural products to bring more of the earth\'s finest to your table. Stay close - the next harvest is already underway.',
        benefits: [
          'New crop varieties in development',
          'Expanding into processing and packaging',
          'Export-ready product lines',
          'Partnering with global distributors',
        ],
        icon: 'sprout',
        color: '#2D9960',
        bgColor: '#EDF7F1',
        available: false,
      },
    ] as Product[],
  }),

  getters: {
    availableProducts: (state) => state.products.filter((p) => p.available && p.category !== 'coming-soon'),
    allProducts: (state) => state.products,
    getProductById: (state) => (id: string) => state.products.find((p) => p.id === id),
  },
})
